/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as TemaRouteImport } from './routes/tema'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBannersRouteImport } from './routes/admin/banners'
import { Route as AdminFaqsRouteImport } from './routes/admin/faqs'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminPackagesRouteImport } from './routes/admin/packages'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardLoginRouteImport } from './routes/dashboard/login'
import { Route as DashboardRegisterRouteImport } from './routes/dashboard/register'
import { Route as AdminThemesThemeIdRouteImport } from './routes/admin/themes/$themeId'
import { Route as AdminThemesNewRouteImport } from './routes/admin/themes/new'
import { Route as DashboardInvitationsInvitationIdRouteImport } from './routes/dashboard/invitations/$invitationId'
import { Route as DashboardInvitationsNewRouteImport } from './routes/dashboard/invitations/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TemaRoute = TemaRouteImport.update({
  id: '/tema',
  path: '/tema',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/admin/banners',
  path: '/admin/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/admin/faqs',
  path: '/admin/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/admin/packages',
  path: '/admin/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/dashboard/login',
  path: '/dashboard/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRegisterRoute = DashboardRegisterRouteImport.update({
  id: '/dashboard/register',
  path: '/dashboard/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminThemesThemeIdRoute = AdminThemesThemeIdRouteImport.update({
  id: '/admin/themes/$themeId',
  path: '/admin/themes/$themeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminThemesNewRoute = AdminThemesNewRouteImport.update({
  id: '/admin/themes/new',
  path: '/admin/themes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInvitationsInvitationIdRoute =
  DashboardInvitationsInvitationIdRouteImport.update({
    id: '/dashboard/invitations/$invitationId',
    path: '/dashboard/invitations/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardInvitationsNewRoute = DashboardInvitationsNewRouteImport.update({
  id: '/dashboard/invitations/new',
  path: '/dashboard/invitations/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/tema': typeof TemaRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/register': typeof DashboardRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/themes/$themeId': typeof AdminThemesThemeIdRoute
  '/admin/themes/new': typeof AdminThemesNewRoute
  '/dashboard/invitations/$invitationId': typeof DashboardInvitationsInvitationIdRoute
  '/dashboard/invitations/new': typeof DashboardInvitationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/tema': typeof TemaRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/register': typeof DashboardRegisterRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/themes/$themeId': typeof AdminThemesThemeIdRoute
  '/admin/themes/new': typeof AdminThemesNewRoute
  '/dashboard/invitations/$invitationId': typeof DashboardInvitationsInvitationIdRoute
  '/dashboard/invitations/new': typeof DashboardInvitationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/tema': typeof TemaRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/register': typeof DashboardRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/themes/$themeId': typeof AdminThemesThemeIdRoute
  '/admin/themes/new': typeof AdminThemesNewRoute
  '/dashboard/invitations/$invitationId': typeof DashboardInvitationsInvitationIdRoute
  '/dashboard/invitations/new': typeof DashboardInvitationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/tema'
    | '/admin/banners'
    | '/admin/faqs'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/users'
    | '/dashboard/login'
    | '/dashboard/register'
    | '/admin/'
    | '/dashboard/'
    | '/admin/themes/$themeId'
    | '/admin/themes/new'
    | '/dashboard/invitations/$invitationId'
    | '/dashboard/invitations/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/tema'
    | '/admin/banners'
    | '/admin/faqs'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/users'
    | '/dashboard/login'
    | '/dashboard/register'
    | '/admin'
    | '/dashboard'
    | '/admin/themes/$themeId'
    | '/admin/themes/new'
    | '/dashboard/invitations/$invitationId'
    | '/dashboard/invitations/new'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/tema'
    | '/admin/banners'
    | '/admin/faqs'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/users'
    | '/dashboard/login'
    | '/dashboard/register'
    | '/admin/'
    | '/dashboard/'
    | '/admin/themes/$themeId'
    | '/admin/themes/new'
    | '/dashboard/invitations/$invitationId'
    | '/dashboard/invitations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  TemaRoute: typeof TemaRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardRegisterRoute: typeof DashboardRegisterRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  AdminThemesThemeIdRoute: typeof AdminThemesThemeIdRoute
  AdminThemesNewRoute: typeof AdminThemesNewRoute
  DashboardInvitationsInvitationIdRoute: typeof DashboardInvitationsInvitationIdRoute
  DashboardInvitationsNewRoute: typeof DashboardInvitationsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tema': {
      id: '/tema'
      path: '/tema'
      fullPath: '/tema'
      preLoaderRoute: typeof TemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/admin/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/admin/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/dashboard/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/register': {
      id: '/dashboard/register'
      path: '/dashboard/register'
      fullPath: '/dashboard/register'
      preLoaderRoute: typeof DashboardRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/themes/$themeId': {
      id: '/admin/themes/$themeId'
      path: '/admin/themes/$themeId'
      fullPath: '/admin/themes/$themeId'
      preLoaderRoute: typeof AdminThemesThemeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/themes/new': {
      id: '/admin/themes/new'
      path: '/admin/themes/new'
      fullPath: '/admin/themes/new'
      preLoaderRoute: typeof AdminThemesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/invitations/$invitationId': {
      id: '/dashboard/invitations/$invitationId'
      path: '/dashboard/invitations/$invitationId'
      fullPath: '/dashboard/invitations/$invitationId'
      preLoaderRoute: typeof DashboardInvitationsInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/invitations/new': {
      id: '/dashboard/invitations/new'
      path: '/dashboard/invitations/new'
      fullPath: '/dashboard/invitations/new'
      preLoaderRoute: typeof DashboardInvitationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  TemaRoute: TemaRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminUsersRoute: AdminUsersRoute,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardRegisterRoute: DashboardRegisterRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AdminThemesThemeIdRoute: AdminThemesThemeIdRoute,
  AdminThemesNewRoute: AdminThemesNewRoute,
  DashboardInvitationsInvitationIdRoute: DashboardInvitationsInvitationIdRoute,
  DashboardInvitationsNewRoute: DashboardInvitationsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
